name: prakash-learnings

on: [push, pull_request]

env:
  MYVAR: ${{ github.actor }}
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "SriKrishna Prakash"
      - name: step2
        run : |
          echo "${{ github.token }}"
          echo "${MYVAR}"
